ktor:
  deployment:
    port: 8080
    host: 127.0.0.1
  application:
    modules:
      - com.coyotebitcoin.tatooine.ApplicationKt.module

faucet:
  bearerToken: "token"
  amount: 5000
  versionName: "2.1.0 Tatooine Regtest"

# This config defaults to a local Regtest setup with an Electrum client
wallet:
  descriptor: "wpkh(tprv8ZgxMBicQKsPeqkztELFj4aDR1P3U2fc8k56wgujCurY8pmKDPGN5RKjF1ENNWxcWygdFuiWzBWT1zP2AQcSjZC3u9UfQjciisdLwL58kdk/84h/1h/0h/0/*)"
  network: "REGTEST" # One of REGTEST, SIGNET, TESTNET, TESTNET4
  electrumUrl: "tcp://127.0.0.1:60401"
  syncType: "ELECTRUM" # One of "CBF" or "ELECTRUM"
